version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosec
    - bodyclose
    - ineffassign
    - gocritic

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
      - (*sql.DB).Close
      - (*sql.Rows).Close

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
