package client

import (
	"context"

	"github.com/mtgo-labs/mtgo/tg"
)

// rpcInvoker is the subset of *tg.RPCClient used by client handlers.
// In production, Client.rpc is a *tg.RPCClient (which satisfies this
// interface). In tests, a fakeRPC double can be injected to unit-test
// handlers without a live Telegram connection.
type rpcInvoker interface {
	AccountGetBotBusinessConnection(ctx context.Context, req *tg.AccountGetBotBusinessConnectionRequest) (tg.UpdatesClass, error)
	AuthLogOut(ctx context.Context) (*tg.AuthLoggedOut, error)
	BotsAnswerWebhookJSONQuery(ctx context.Context, req *tg.BotsAnswerWebhookJSONQueryRequest) (bool, error)
	BotsEditAccessSettings(ctx context.Context, req *tg.BotsEditAccessSettingsRequest) (bool, error)
	BotsExportBotToken(ctx context.Context, req *tg.BotsExportBotTokenRequest) (*tg.BotsExportedBotToken, error)
	BotsGetAccessSettings(ctx context.Context, req *tg.BotsGetAccessSettingsRequest) (*tg.BotsAccessSettings, error)
	BotsGetBotInfo(ctx context.Context, req *tg.BotsGetBotInfoRequest) (tg.BotInfoClass, error)
	BotsGetBotCommands(ctx context.Context, req *tg.BotsGetBotCommandsRequest) (tg.TLObject, error)
	BotsGetBotMenuButton(ctx context.Context, req *tg.BotsGetBotMenuButtonRequest) (tg.BotMenuButtonClass, error)
	BotsRequestWebViewButton(ctx context.Context, req *tg.BotsRequestWebViewButtonRequest) (*tg.BotsRequestedButton, error)
	BotsResetBotCommands(ctx context.Context, req *tg.BotsResetBotCommandsRequest) (bool, error)
	BotsSendCustomRequest(ctx context.Context, req *tg.BotsSendCustomRequestRequest) (*tg.DataJSON, error)
	BotsSetBotBroadcastDefaultAdminRights(ctx context.Context, req *tg.BotsSetBotBroadcastDefaultAdminRightsRequest) (bool, error)
	BotsSetBotCommands(ctx context.Context, req *tg.BotsSetBotCommandsRequest) (bool, error)
	BotsSetBotGroupDefaultAdminRights(ctx context.Context, req *tg.BotsSetBotGroupDefaultAdminRightsRequest) (bool, error)
	BotsSetBotInfo(ctx context.Context, req *tg.BotsSetBotInfoRequest) (bool, error)
	BotsSetBotMenuButton(ctx context.Context, req *tg.BotsSetBotMenuButtonRequest) (bool, error)
	BotsSetCustomVerification(ctx context.Context, req *tg.BotsSetCustomVerificationRequest) (bool, error)
	BotsSetJoinChatResults(ctx context.Context, req *tg.BotsSetJoinChatResultsRequest) (bool, error)
	BotsUpdateUserEmojiStatus(ctx context.Context, req *tg.BotsUpdateUserEmojiStatusRequest) (bool, error)
	ChannelsDeleteMessages(ctx context.Context, req *tg.ChannelsDeleteMessagesRequest) (*tg.MessagesAffectedMessages, error)
	ChannelsDeleteParticipantHistory(ctx context.Context, req *tg.ChannelsDeleteParticipantHistoryRequest) (*tg.MessagesAffectedHistory, error)
	ChannelsEditAdmin(ctx context.Context, req *tg.ChannelsEditAdminRequest) (tg.UpdatesClass, error)
	ChannelsEditBanned(ctx context.Context, req *tg.ChannelsEditBannedRequest) (tg.UpdatesClass, error)
	ChannelsEditPhoto(ctx context.Context, req *tg.ChannelsEditPhotoRequest) (tg.UpdatesClass, error)
	ChannelsEditTitle(ctx context.Context, req *tg.ChannelsEditTitleRequest) (tg.UpdatesClass, error)
	ChannelsGetFullChannel(ctx context.Context, req *tg.ChannelsGetFullChannelRequest) (tg.ChatFullClass, error)
	ChannelsGetMessages(ctx context.Context, req *tg.ChannelsGetMessagesRequest) (tg.MessagesClass, error)
	ChannelsGetParticipant(ctx context.Context, req *tg.ChannelsGetParticipantRequest) (tg.ChannelParticipantClass, error)
	ChannelsGetParticipants(ctx context.Context, req *tg.ChannelsGetParticipantsRequest) (tg.ChannelParticipantsClass, error)
	ChannelsLeaveChannel(ctx context.Context, req *tg.ChannelsLeaveChannelRequest) (tg.UpdatesClass, error)
	ChannelsSetStickers(ctx context.Context, req *tg.ChannelsSetStickersRequest) (bool, error)
	ContactsResolveUsername(ctx context.Context, req *tg.ContactsResolveUsernameRequest) (*tg.ContactsResolvedPeer, error)
	HelpSetBotUpdatesStatus(ctx context.Context, req *tg.HelpSetBotUpdatesStatusRequest) (bool, error)
	InvokeWithBusinessConnection(ctx context.Context, req *tg.InvokeWithBusinessConnectionRequest) (tg.TLObject, error)
	MessagesCreateForumTopic(ctx context.Context, req *tg.MessagesCreateForumTopicRequest) (tg.UpdatesClass, error)
	MessagesDeleteChatUser(ctx context.Context, req *tg.MessagesDeleteChatUserRequest) (tg.UpdatesClass, error)
	MessagesDeleteMessages(ctx context.Context, req *tg.MessagesDeleteMessagesRequest) (*tg.MessagesAffectedMessages, error)
	MessagesDeleteParticipantReaction(ctx context.Context, req *tg.MessagesDeleteParticipantReactionRequest) (tg.UpdatesClass, error)
	MessagesDeleteParticipantReactions(ctx context.Context, req *tg.MessagesDeleteParticipantReactionsRequest) (bool, error)
	MessagesDeleteTopicHistory(ctx context.Context, req *tg.MessagesDeleteTopicHistoryRequest) (*tg.MessagesAffectedHistory, error)
	MessagesEditChatAbout(ctx context.Context, req *tg.MessagesEditChatAboutRequest) (bool, error)
	MessagesEditChatDefaultBannedRights(ctx context.Context, req *tg.MessagesEditChatDefaultBannedRightsRequest) (tg.UpdatesClass, error)
	MessagesEditChatParticipantRank(ctx context.Context, req *tg.MessagesEditChatParticipantRankRequest) (tg.UpdatesClass, error)
	MessagesEditChatPhoto(ctx context.Context, req *tg.MessagesEditChatPhotoRequest) (tg.UpdatesClass, error)
	MessagesEditChatTitle(ctx context.Context, req *tg.MessagesEditChatTitleRequest) (tg.UpdatesClass, error)
	MessagesEditExportedChatInvite(ctx context.Context, req *tg.MessagesEditExportedChatInviteRequest) (tg.ExportedChatInviteClass, error)
	MessagesEditForumTopic(ctx context.Context, req *tg.MessagesEditForumTopicRequest) (tg.UpdatesClass, error)
	MessagesEditInlineBotMessage(ctx context.Context, req *tg.MessagesEditInlineBotMessageRequest) (bool, error)
	MessagesEditMessage(ctx context.Context, req *tg.MessagesEditMessageRequest) (tg.UpdatesClass, error)
	MessagesExportChatInvite(ctx context.Context, req *tg.MessagesExportChatInviteRequest) (tg.ExportedChatInviteClass, error)
	MessagesForwardMessages(ctx context.Context, req *tg.MessagesForwardMessagesRequest) (tg.UpdatesClass, error)
	MessagesGetCustomEmojiDocuments(ctx context.Context, req *tg.MessagesGetCustomEmojiDocumentsRequest) (tg.TLObject, error)
	MessagesGetDialogs(ctx context.Context, req *tg.MessagesGetDialogsRequest) (tg.DialogsClass, error)
	MessagesGetFullChat(ctx context.Context, req *tg.MessagesGetFullChatRequest) (tg.ChatFullClass, error)
	MessagesGetGameHighScores(ctx context.Context, req *tg.MessagesGetGameHighScoresRequest) (*tg.MessagesHighScores, error)
	MessagesGetInlineGameHighScores(ctx context.Context, req *tg.MessagesGetInlineGameHighScoresRequest) (*tg.MessagesHighScores, error)
	MessagesGetMessages(ctx context.Context, req *tg.MessagesGetMessagesRequest) (tg.MessagesClass, error)
	MessagesGetPersonalChannelHistory(ctx context.Context, req *tg.MessagesGetPersonalChannelHistoryRequest) (tg.MessagesClass, error)
	MessagesGetStickerSet(ctx context.Context, req *tg.MessagesGetStickerSetRequest) (tg.StickerSetClass, error)
	MessagesHideChatJoinRequest(ctx context.Context, req *tg.MessagesHideChatJoinRequestRequest) (tg.UpdatesClass, error)
	MessagesSavePreparedInlineMessage(ctx context.Context, req *tg.MessagesSavePreparedInlineMessageRequest) (*tg.MessagesBotPreparedInlineMessage, error)
	MessagesSendMedia(ctx context.Context, req *tg.MessagesSendMediaRequest) (tg.UpdatesClass, error)
	MessagesSendMessage(ctx context.Context, req *tg.MessagesSendMessageRequest) (tg.UpdatesClass, error)
	MessagesSendMultiMedia(ctx context.Context, req *tg.MessagesSendMultiMediaRequest) (tg.UpdatesClass, error)
	MessagesSendReaction(ctx context.Context, req *tg.MessagesSendReactionRequest) (tg.UpdatesClass, error)
	MessagesSendWebViewResultMessage(ctx context.Context, req *tg.MessagesSendWebViewResultMessageRequest) (*tg.WebViewMessageSent, error)
	MessagesSetBotCallbackAnswer(ctx context.Context, req *tg.MessagesSetBotCallbackAnswerRequest) (bool, error)
	MessagesSetBotGuestChatResult(ctx context.Context, req *tg.MessagesSetBotGuestChatResultRequest) (tg.InputBotInlineMessageIDClass, error)
	MessagesSetGameScore(ctx context.Context, req *tg.MessagesSetGameScoreRequest) (tg.UpdatesClass, error)
	MessagesSetInlineBotResults(ctx context.Context, req *tg.MessagesSetInlineBotResultsRequest) (bool, error)
	MessagesSetInlineGameScore(ctx context.Context, req *tg.MessagesSetInlineGameScoreRequest) (bool, error)
	MessagesSetTyping(ctx context.Context, req *tg.MessagesSetTypingRequest) (bool, error)
	MessagesToggleSuggestedPostApproval(ctx context.Context, req *tg.MessagesToggleSuggestedPostApprovalRequest) (tg.UpdatesClass, error)
	MessagesUnpinAllMessages(ctx context.Context, req *tg.MessagesUnpinAllMessagesRequest) (*tg.MessagesAffectedHistory, error)
	MessagesUpdatePinnedMessage(ctx context.Context, req *tg.MessagesUpdatePinnedMessageRequest) (tg.UpdatesClass, error)
	MessagesUploadMedia(ctx context.Context, req *tg.MessagesUploadMediaRequest) (tg.MessageMediaClass, error)
	PaymentsChangeStarsSubscription(ctx context.Context, req *tg.PaymentsChangeStarsSubscriptionRequest) (bool, error)
	PaymentsConvertStarGift(ctx context.Context, req *tg.PaymentsConvertStarGiftRequest) (bool, error)
	PaymentsExportInvoice(ctx context.Context, req *tg.PaymentsExportInvoiceRequest) (*tg.PaymentsExportedInvoice, error)
	PaymentsGetPaymentForm(ctx context.Context, req *tg.PaymentsGetPaymentFormRequest) (tg.PaymentFormClass, error)
	PaymentsGetSavedStarGifts(ctx context.Context, req *tg.PaymentsGetSavedStarGiftsRequest) (*tg.PaymentsSavedStarGifts, error)
	PaymentsGetStarGifts(ctx context.Context, req *tg.PaymentsGetStarGiftsRequest) (tg.StarGiftsClass, error)
	PaymentsGetStarsTransactions(ctx context.Context, req *tg.PaymentsGetStarsTransactionsRequest) (*tg.PaymentsStarsStatus, error)
	PaymentsRefundStarsCharge(ctx context.Context, req *tg.PaymentsRefundStarsChargeRequest) (tg.UpdatesClass, error)
	PaymentsSendStarsForm(ctx context.Context, req *tg.PaymentsSendStarsFormRequest) (tg.PaymentResultClass, error)
	PaymentsTransferStarGift(ctx context.Context, req *tg.PaymentsTransferStarGiftRequest) (tg.UpdatesClass, error)
	PaymentsUpgradeStarGift(ctx context.Context, req *tg.PaymentsUpgradeStarGiftRequest) (tg.UpdatesClass, error)
	PhotosDeletePhotos(ctx context.Context, req *tg.PhotosDeletePhotosRequest) (tg.TLObject, error)
	PhotosGetUserPhotos(ctx context.Context, req *tg.PhotosGetUserPhotosRequest) (tg.PhotosClass, error)
	PhotosUploadProfilePhoto(ctx context.Context, req *tg.PhotosUploadProfilePhotoRequest) (tg.PhotoClass, error)
	PremiumGetUserBoosts(ctx context.Context, req *tg.PremiumGetUserBoostsRequest) (*tg.PremiumBoostsList, error)
	StickersAddStickerToSet(ctx context.Context, req *tg.StickersAddStickerToSetRequest) (tg.StickerSetClass, error)
	StickersChangeSticker(ctx context.Context, req *tg.StickersChangeStickerRequest) (tg.StickerSetClass, error)
	StickersChangeStickerPosition(ctx context.Context, req *tg.StickersChangeStickerPositionRequest) (tg.StickerSetClass, error)
	StickersCreateStickerSet(ctx context.Context, req *tg.StickersCreateStickerSetRequest) (tg.StickerSetClass, error)
	StickersDeleteStickerSet(ctx context.Context, req *tg.StickersDeleteStickerSetRequest) (bool, error)
	StickersRemoveStickerFromSet(ctx context.Context, req *tg.StickersRemoveStickerFromSetRequest) (tg.StickerSetClass, error)
	StickersRenameStickerSet(ctx context.Context, req *tg.StickersRenameStickerSetRequest) (tg.StickerSetClass, error)
	StickersReplaceSticker(ctx context.Context, req *tg.StickersReplaceStickerRequest) (tg.StickerSetClass, error)
	StickersSetStickerSetThumb(ctx context.Context, req *tg.StickersSetStickerSetThumbRequest) (tg.StickerSetClass, error)
	StoriesDeleteStories(ctx context.Context, req *tg.StoriesDeleteStoriesRequest) (tg.TLObject, error)
	StoriesEditStory(ctx context.Context, req *tg.StoriesEditStoryRequest) (tg.UpdatesClass, error)
	StoriesSendStory(ctx context.Context, req *tg.StoriesSendStoryRequest) (tg.UpdatesClass, error)
	UploadGetFile(ctx context.Context, req *tg.UploadGetFileRequest) (tg.FileClass, error)
	UploadGetWebFile(ctx context.Context, req *tg.UploadGetWebFileRequest) (*tg.UploadWebFile, error)
	UploadSaveBigFilePart(ctx context.Context, req *tg.UploadSaveBigFilePartRequest) (bool, error)
	UploadSaveFilePart(ctx context.Context, req *tg.UploadSaveFilePartRequest) (bool, error)
	UsersGetFullUser(ctx context.Context, req *tg.UsersGetFullUserRequest) (tg.UserFullClass, error)
	UsersGetSavedMusic(ctx context.Context, req *tg.UsersGetSavedMusicRequest) (tg.SavedMusicClass, error)
	UsersSetSecureValueErrors(ctx context.Context, req *tg.UsersSetSecureValueErrorsRequest) (bool, error)
}
