package client

import (
	"context"
	"crypto/rand"
	"io"
	"math/big"

	"github.com/mtgo-labs/mtgo/tg"
)

const (
	// partSize is 512KB — the chunk size for upload.saveFilePart / saveBigFilePart.
	partSize = 512 * 1024
	// bigFileThreshold is TDLib's SMALL_FILE_MAX_SIZE (FileType.cpp:365): files
	// files at or above this size must be uploaded via upload.saveBigFilePart + inputFileBig;
	// smaller files use upload.saveFilePart + inputFile. Mirrors is_file_big
	// (FileType.cpp:349).
	bigFileThreshold = 10 << 20
)

// uploadFile reads data from r, chunks it into 512KB parts, and uploads each
// part. Files larger than bigFileThreshold use upload.saveBigFilePart and are
// returned as InputFileBig; smaller files use upload.saveFilePart and InputFile.
// size is the total file size (drives the big/small decision and the
// saveBigFilePart file_total_parts). fileID is a random int64 generated by the
// caller and shared across all parts (MTProto protocol requirement).
func (c *Client) uploadFile(ctx context.Context, fileID int64, name string, size int64, r io.Reader) (tg.InputFileClass, error) {
	big := size >= bigFileThreshold
	totalParts := int32((size + partSize - 1) / partSize)
	buf := make([]byte, partSize)
	var part int32
	for {
		n, readErr := io.ReadFull(r, buf)
		if n > 0 {
			if big {
				if _, err := c.rpc.UploadSaveBigFilePart(ctx, &tg.UploadSaveBigFilePartRequest{
					FileID:         fileID,
					FilePart:       part,
					FileTotalParts: totalParts,
					Bytes:          buf[:n],
				}); err != nil {
					return nil, err
				}
			} else {
				if _, err := c.rpc.UploadSaveFilePart(ctx, &tg.UploadSaveFilePartRequest{
					FileID:   fileID,
					FilePart: part,
					Bytes:    buf[:n],
				}); err != nil {
					return nil, err
				}
			}
			part++
		}
		if readErr == io.EOF || readErr == io.ErrUnexpectedEOF {
			break
		}
		if readErr != nil {
			return nil, readErr
		}
	}
	if part == 0 {
		return nil, &Error{Code: 400, Description: "Bad Request: file is empty"}
	}
	if big {
		return &tg.InputFileBig{ID: fileID, Parts: part, Name: name}, nil
	}
	return &tg.InputFile{ID: fileID, Parts: part, Name: name}, nil
}

// generateFileID generates a random int64 for use as an MTProto file_id.
func generateFileID() (int64, error) {
	n, err := rand.Int(rand.Reader, big.NewInt(1<<62))
	if err != nil {
		return 0, err
	}
	return n.Int64(), nil
}
